#ifndef LH_ATTRIBUTE_FORCE_INLINE_H
#define LH_ATTRIBUTE_FORCE_INLINE_H

#include <lh/compiler.h>

#define LH_ATTRIBUTE_FORCE_INLINE LH_COMPILER_ATTRIBUTE_FORCE_INLINE

#endif // LH_ATTRIBUTE_FORCE_INLINE_H