#ifndef LH_ATTRIBUTE_SYMBOL_H
#define LH_ATTRIBUTE_SYMBOL_H

#include <lh/compiler.h>
#include <lh/library_option_fallback.h>

#if (LH_LIBRARY_OPTION_STATIC_BUILD == LH_LIBRARY_OPTION_ON)
#    define LH_ATTRIBUTE_SYMBOL
#elif (LH_LIBRARY_OPTION_SHARED_BUILD == LH_LIBRARY_OPTION_ON)
#    define LH_ATTRIBUTE_SYMBOL LH_COMPILER_ATTRIBUTE_SYMBOL_EXPORT
#else
#    define LH_ATTRIBUTE_SYMBOL LH_COMPILER_ATTRIBUTE_SYMBOL_IMPORT
#endif

#endif // LH_ATTRIBUTE_SYMBOL_H