#ifndef LH_ATTRIBUTE_THREAD_LOCAL_H
#define LH_ATTRIBUTE_THREAD_LOCAL_H

#include "library_option_fallback.h"
#include <lh/compiler.h>

#if (LH_LIBRARY_OPTION_THREAD_LOCAL == LH_LIBRARY_OPTION_ON)
#    define LH_ATTRIBUTE_THREAD_LOCAL LH_COMPILER_ATTRIBUTE_THREAD_LOCAL
#elif (LH_LIBRARY_OPTION_THREAD_LOCAL == LH_LIBRARY_OPTION_OFF)
#    define LH_ATTRIBUTE_THREAD_LOCAL
#endif

#endif // LH_ATTRIBUTE_THREAD_LOCAL_H