#ifndef LH_COMPILER_ATTRIBUTE_INLINE_H
#define LH_COMPILER_ATTRIBUTE_INLINE_H

#ifndef LH_COMPILER_ATTRIBUTE_INLINE
#    define LH_COMPILER_ATTRIBUTE_INLINE inline
#endif // LH_COMPILER_ATTRIBUTE_INLINE

#endif // LH_COMPILER_ATTRIBUTE_INLINE_H