#ifndef LH_COMPILER_ATTRIBUTE_THREAD_LOCAL_H
#define LH_COMPILER_ATTRIBUTE_THREAD_LOCAL_H

#include <lh/compiler_type.h>

#if (LH_COMPILER_TYPE_IS_GCC_LIKE)
#    define LH_COMPILER_ATTRIBUTE_THREAD_LOCAL __thread
#elif (LH_COMPILER_TYPE == LH_COMPILER_TYPE_MSVC)
#    define LH_COMPILER_ATTRIBUTE_THREAD_LOCAL __declspec(thread)
#endif

#endif // LH_COMPILER_ATTRIBUTE_THREAD_LOCAL_H
