/* Generated by scripts/font.py.
 * Source: Roboto-Regular.ttf  size: 16px  bpp: 4
 * Range: 32..126  line: 22px  ascent: 17  glyphs cropped to ink
 * Rows are packed high-bit first, the same way LVGL's font converter packs them.
 * Roboto is Copyright 2011 Google Inc. and licensed under the Apache License 2.0.
 */
#ifndef LH_UI_FONT_ROBOTO_H
#define LH_UI_FONT_ROBOTO_H

#include <lh/byte.h>
#include <lh/compiler/extern/c.h>
#include <lh/ui/font.h>
#include <lh/ui/mask.h>

LH_COMPILER_EXTERN_C_BEGIN

/** Packed glyph coverage of ::lh_ui_font_roboto (glyphs are slices of this). */
extern const lh_byte_t lh_ui_font_roboto_bits[];

/** Cropped masks of ::lh_ui_font_roboto, one per code. */
extern const lh_ui_mask_t lh_ui_font_roboto_glyphs[];

/** One advance byte per glyph of ::lh_ui_font_roboto. */
extern const lh_byte_t lh_ui_font_roboto_advances[];

/** Mask top relative to the baseline per glyph of ::lh_ui_font_roboto. */
extern const lh_s32_t lh_ui_font_roboto_tops[];

/** Roboto-Regular at 16px, codes 32..126, 4 bits per pixel. */
extern const lh_ui_font_t lh_ui_font_roboto;

LH_COMPILER_EXTERN_C_END

#endif /* LH_UI_FONT_ROBOTO_H */
