/* Generated by scripts/font.py.
 * Source: Roboto-Regular.ttf  size: 16px  bpp: 4
 * Languages: ru
 * Ranges (7): U+0020-007E U+00A0-00AC U+00AE-00B7 U+00B9-00BF U+0400-045F U+2013-2014 U+2116-2116
 * Glyphs: 224  line: 22px  ascent: 17  cap: 12  glyphs cropped to ink
 * Rows are packed high-bit first, the same way LVGL's font converter packs them.
 * Roboto is Copyright 2011 Google Inc. and licensed under the Apache License 2.0.
 */
#ifndef LH_UI_FONT_ROBOTO_H
#define LH_UI_FONT_ROBOTO_H

#include <lh/byte.h>
#include <lh/compiler/extern/c.h>
#include <lh/ui/font.h>
#include <lh/ui/mask.h>

LH_COMPILER_EXTERN_C_BEGIN

/** Packed glyph coverage of ::lh_ui_font_roboto (glyphs are slices of this). */
extern const lh_byte_t lh_ui_font_roboto_bits[];

/** Cropped masks of ::lh_ui_font_roboto, one per code. */
extern const lh_ui_mask_t lh_ui_font_roboto_glyphs[];

/** One advance byte per glyph of ::lh_ui_font_roboto. */
extern const lh_byte_t lh_ui_font_roboto_advances[];

/** Mask top relative to the baseline per glyph of ::lh_ui_font_roboto. */
extern const lh_s32_t lh_ui_font_roboto_tops[];

/** The runs of code points of ::lh_ui_font_roboto, in table order. */
extern const lh_ui_font_range_t lh_ui_font_roboto_ranges[];

/** Roboto-Regular at 16px, 224 glyphs over 7 run(s): U+0020-007E U+00A0-00AC U+00AE-00B7 U+00B9-00BF U+0400-045F U+2013-2014 U+2116-2116
 *  (4 bits per pixel). */
extern const lh_ui_font_t lh_ui_font_roboto;

LH_COMPILER_EXTERN_C_END

#endif /* LH_UI_FONT_ROBOTO_H */
