#!/usr/bin/env python3
"""Turn a TTF/OTF into a C font the canvas can draw from memory.

Same knobs as LVGL's font converter (lv_font_conv): a font file, a pixel
size, bits per pixel, and the characters to keep. The bitmap is packed
the same way: each row starts at the high bit, bpp is 1, 2, 4 or 8, and
the row is padded to a whole byte. The result is an lh_ui_font_t over
those bytes, not an operating-system font.
"""

import argparse
import sys
from pathlib import Path


def identifier(name):
    cleaned = []
    for ch in name:
        cleaned.append(ch if ch.isalnum() else "_")
    text = "".join(cleaned)
    if not text or text[0].isdigit():
        text = "font_" + text
    return text


def parse_range(text):
    codes = []
    for part in text.split(","):
        piece = part.strip()
        if not piece:
            continue
        if "-" in piece:
            start, end = piece.split("-", 1)
            first = int(start, 0)
            last = int(end, 0)
            codes.extend(range(first, last + 1))
        else:
            codes.append(int(piece, 0))
    return codes


def pack_row(values, bpp):
    row = []
    accumulator = 0
    filled = 0
    for value in values:
        accumulator = (accumulator << bpp) | value
        filled += bpp
        if filled == 8:
            row.append(accumulator)
            accumulator = 0
            filled = 0
    if filled:
        row.append(accumulator << (8 - filled))
    return row


def write_bytes(lines, values, per_line):
    row = []
    for value in values:
        row.append(f"0x{value:02X}")
        if len(row) == per_line:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")


def main():
    parser = argparse.ArgumentParser(description="TTF/OTF to an lh font")
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--size", required=True, type=int)
    parser.add_argument("--bpp", default=4, type=int, choices=[1, 2, 4, 8])
    parser.add_argument("--range", default="32-126", help="Code points, e.g. 32-126,48")
    parser.add_argument("--symbols", default="", help="Extra characters, kept in order")
    parser.add_argument("--name", help="C identifier, default is the file stem plus size")
    parser.add_argument("-o", "--output", required=True, type=Path)
    args = parser.parse_args()

    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("font.py needs Pillow: pip install pillow", file=sys.stderr)
        return 1

    codes = parse_range(args.range)
    for ch in args.symbols:
        code = ord(ch)
        if code not in codes:
            codes.append(code)
    codes = [code for code in codes if 0 <= code <= 255]
    if not codes:
        print("no characters in 0..255", file=sys.stderr)
        return 1
    first = min(codes)
    last = max(codes)
    # The font is a dense run from the first code to the last, like LVGL's
    # format-0 cmap. Missing codes inside the run are blank cells.
    count = last - first + 1

    face = ImageFont.truetype(str(args.font), args.size)
    ascent, descent = face.getmetrics()
    height = ascent + descent
    if height <= 0:
        print("font size has no line height", file=sys.stderr)
        return 1

    levels = (1 << args.bpp) - 1
    cell_width = 1
    rendered = {}
    advances = [0] * count
    for code in range(first, last + 1):
        ch = chr(code)
        advance = int(round(face.getlength(ch)))
        if advance > 255:
            print(f"advance of U+{code:04X} is {advance}, wider than a byte", file=sys.stderr)
            return 1
        advances[code - first] = advance
        bbox = face.getbbox(ch)
        ink = 0 if bbox is None else bbox[2]
        cell_width = max(cell_width, advance, ink)

    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        plate = Image.new("L", (cell_width, height), 0)
        ImageDraw.Draw(plate).text((0, ascent), ch, font=face, fill=255, anchor="ls")
        samples = plate.get_flattened_data() if hasattr(plate, "get_flattened_data") else plate.getdata()
        raw = list(samples)
        for y in range(height):
            row = []
            for x in range(cell_width):
                pixel = raw[y * cell_width + x]
                row.append((pixel * levels + 127) // 255)
            glyphs.extend(pack_row(row, args.bpp))

    row_bytes = (cell_width * args.bpp + 7) // 8
    name = identifier(args.name or f"{args.font.stem}_{args.size}")
    lines = [
        "/* Generated by scripts/font.py.",
        f" * Source: {args.font.name}  size: {args.size}px  bpp: {args.bpp}",
        f" * Range: {first}..{last}  cell: {cell_width}x{height}  row: {row_bytes} bytes",
        " * Rows are packed high-bit first, the same way LVGL's font converter packs them.",
        " */",
        "#include <lh/ui/font.h>",
        "#include <lh/memory/view/initializer.h>",
        "",
        f"static const lh_byte_t {name}_glyphs[] = {{",
    ]
    write_bytes(lines, glyphs, 12)
    lines.append("};")
    lines.append("")
    lines.append(f"static const lh_byte_t {name}_advances[] = {{")
    write_bytes(lines, advances, 12)
    lines += [
        "};",
        "",
        f"const lh_ui_font_t {name} = {{",
        f"    lh_memory_view_initializer({name}_glyphs, {name}_glyphs + sizeof {name}_glyphs),",
        f"    lh_memory_view_initializer({name}_advances, {name}_advances + sizeof {name}_advances),",
        f"    {cell_width}, {height}, {row_bytes}, {args.bpp}, {first}, {count}",
        "};",
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"{args.output} {cell_width}x{height} bpp {args.bpp} codes {first}..{last}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
