#!/usr/bin/env python3
"""Turn a PNG into a C array of straight RGBA bytes.

Same job as LVGL's LVGLImage.py: a picture in, a color format, a C file
out. The bytes match lh_ui_color_t (red, green, blue, alpha, not
premultiplied), which is the memory a canvas already draws. ARGB8888,
RGB888, A8 and L8 are the formats that land on those four channels.
PNG is read with the standard library, so the script has no package to
install.
"""

import argparse
import struct
import sys
import zlib
from pathlib import Path


def identifier(name):
    cleaned = []
    for ch in name:
        cleaned.append(ch if ch.isalnum() else "_")
    text = "".join(cleaned)
    if not text or text[0].isdigit():
        text = "img_" + text
    return text


def paeth(left, up, upper_left):
    estimate = left + up - upper_left
    nearest = min((abs(estimate - left), left), (abs(estimate - up), up),
                  (abs(estimate - upper_left), upper_left))
    return nearest[1]


def read_png(path):
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path} is not a PNG")
    position = 8
    width = height = bit_depth = color_type = 0
    palette = b""
    transparency = b""
    compressed = b""
    while position < len(data):
        length = struct.unpack(">I", data[position : position + 4])[0]
        kind = data[position + 4 : position + 8]
        chunk = data[position + 8 : position + 8 + length]
        position += 12 + length
        if kind == b"IHDR":
            width, height, bit_depth, color_type = struct.unpack(">IIBB", chunk[:10])
            if chunk[10] != 0:
                raise ValueError("interlaced PNG is not converted")
            if bit_depth != 8:
                raise ValueError("only 8 bits per channel are converted")
        elif kind == b"PLTE":
            palette = chunk
        elif kind == b"tRNS":
            transparency = chunk
        elif kind == b"IDAT":
            compressed += chunk
        elif kind == b"IEND":
            break
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[color_type]
    raw = zlib.decompress(compressed)
    stride = width * channels
    rows = []
    cursor = 0
    previous = [0] * stride
    for _ in range(height):
        filter_kind = raw[cursor]
        cursor += 1
        scan = list(raw[cursor : cursor + stride])
        cursor += stride
        for index, value in enumerate(scan):
            left = scan[index - channels] if index >= channels else 0
            up = previous[index]
            upper_left = previous[index - channels] if index >= channels else 0
            if filter_kind == 1:
                value = (value + left) & 255
            elif filter_kind == 2:
                value = (value + up) & 255
            elif filter_kind == 3:
                value = (value + ((left + up) // 2)) & 255
            elif filter_kind == 4:
                value = (value + paeth(left, up, upper_left)) & 255
            elif filter_kind != 0:
                raise ValueError(f"unknown PNG filter {filter_kind}")
            scan[index] = value
        previous = scan
        rows.append(scan)
    pixels = []
    for scan in rows:
        for x in range(width):
            sample = scan[x * channels : (x + 1) * channels]
            if color_type == 6:
                red, green, blue, alpha = sample
            elif color_type == 2:
                red, green, blue, alpha = sample[0], sample[1], sample[2], 255
            elif color_type == 0:
                red = green = blue = sample[0]
                alpha = 255
            elif color_type == 4:
                red = green = blue = sample[0]
                alpha = sample[1]
            else:
                index = sample[0]
                red, green, blue = palette[index * 3 : index * 3 + 3]
                alpha = transparency[index] if index < len(transparency) else 255
            pixels.append((red, green, blue, alpha))
    return width, height, pixels


def apply_format(pixels, color_format):
    converted = []
    for red, green, blue, alpha in pixels:
        if color_format == "RGB888":
            alpha = 255
        elif color_format == "A8":
            red, green, blue = 255, 255, 255
        elif color_format == "L8":
            red = green = blue = (red * 30 + green * 59 + blue * 11) // 100
            alpha = 255
        converted.append((red, green, blue, alpha))
    return converted


def write_c(path, name, width, height, pixels):
    lines = [
        "/* Generated by scripts/image.py. Straight RGBA, one lh_ui_color_t per pixel. */",
        "#include <lh/ui/color.h>",
        "",
        f"const lh_int_t {name}_width = {width};",
        f"const lh_int_t {name}_height = {height};",
        f"const lh_ui_color_t {name}_pixels[] = {{",
    ]
    row = []
    for red, green, blue, alpha in pixels:
        row.append(f"{{{red}, {green}, {blue}, {alpha}}}")
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="PNG to an lh color array")
    parser.add_argument("--cf", default="ARGB8888", choices=["ARGB8888", "RGB888", "A8", "L8"])
    parser.add_argument("--ofmt", default="C", choices=["C"])
    parser.add_argument("-o", "--output", required=True, help="Output .c file or directory")
    parser.add_argument("--name", help="C identifier, default is the file stem")
    parser.add_argument("files", nargs="+", type=Path)
    args = parser.parse_args()

    output = Path(args.output)
    if len(args.files) == 1:
        width, height, pixels = read_png(args.files[0])
        name = identifier(args.name or args.files[0].stem)
        write_c(output, name, width, height, apply_format(pixels, args.cf))
        print(f"{output} {width}x{height} {args.cf}")
        return 0

    output.mkdir(parents=True, exist_ok=True)
    for source in args.files:
        width, height, pixels = read_png(source)
        name = identifier(source.stem)
        destination = output / (name + ".c")
        write_c(destination, name, width, height, apply_format(pixels, args.cf))
        print(f"{destination} {width}x{height} {args.cf}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
